version: '3.8'

services:
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

  db:
    image: postgres:11.0-alpine
    restart: unless-stopped
    environment:
      BACKEND_DB: postgresql
      POSTGRES_NAME: tcb_db_prod
      POSTGRES_USER: tcb_user_prod
      POSTGRES_PASSWORD: tcb_12345_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/web/tcb_api/django_static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    links:
      - db:db

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/backend/django_static
    depends_on:
      - server
      - redis
    env_file:
      - .env
    links:
      - db:db

volumes:
  static_volume: { }
  postgres_data: { }
