# Generated by Django 4.1.7 on 2023-03-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('experience_year', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('number_students', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Top Teacher',
                'verbose_name_plural': 'Top Teachers',
            },
        ),
    ]
