# Generated by Django 4.1.7 on 2023-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='apartment_letter_en',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_letter_ru',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='apartment_letter_uz',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district_en',
            field=models.CharField(choices=[('MIRZO_ULUGBEK', "MIRZO ULUG'BEK"), ('SHAYXONTOXUR', 'SHAYXONTOXUR'), ('YANGIHAYOT', 'YANGIHAYOT'), ('YAKKASARAY', 'YAKKASARAY'), ('YUNUSOBOD', 'YUNUSOBOD'), ('CHILANZAR', 'CHILANZAR'), ('YASHNOBOD', 'YASHNOBOD'), ('BEKTEMIR', 'BEKTEMIR'), ('MIROBOD', 'MIROBOD'), ('SERGELI', 'SERGELI'), ('OLMAZOR', 'OLMAZOR'), ('UCHTEPA', 'UCHTEPA')], default='YUNUSOBOD', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district_ru',
            field=models.CharField(choices=[('MIRZO_ULUGBEK', "MIRZO ULUG'BEK"), ('SHAYXONTOXUR', 'SHAYXONTOXUR'), ('YANGIHAYOT', 'YANGIHAYOT'), ('YAKKASARAY', 'YAKKASARAY'), ('YUNUSOBOD', 'YUNUSOBOD'), ('CHILANZAR', 'CHILANZAR'), ('YASHNOBOD', 'YASHNOBOD'), ('BEKTEMIR', 'BEKTEMIR'), ('MIROBOD', 'MIROBOD'), ('SERGELI', 'SERGELI'), ('OLMAZOR', 'OLMAZOR'), ('UCHTEPA', 'UCHTEPA')], default='YUNUSOBOD', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='district_uz',
            field=models.CharField(choices=[('MIRZO_ULUGBEK', "MIRZO ULUG'BEK"), ('SHAYXONTOXUR', 'SHAYXONTOXUR'), ('YANGIHAYOT', 'YANGIHAYOT'), ('YAKKASARAY', 'YAKKASARAY'), ('YUNUSOBOD', 'YUNUSOBOD'), ('CHILANZAR', 'CHILANZAR'), ('YASHNOBOD', 'YASHNOBOD'), ('BEKTEMIR', 'BEKTEMIR'), ('MIROBOD', 'MIROBOD'), ('SERGELI', 'SERGELI'), ('OLMAZOR', 'OLMAZOR'), ('UCHTEPA', 'UCHTEPA')], default='YUNUSOBOD', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
