# Generated by Django 4.1.7 on 2023-03-13 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
        ('branch', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center'),
        ),
        migrations.AddField(
            model_name='branch',
            name='courses',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
