# Generated by Django 4.1.7 on 2023-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_branch_name_en_branch_name_ru_branch_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='image',
            field=models.ImageField(upload_to='branches/%Y/%m'),
        ),
    ]
