# Generated by Django 4.1.7 on 2023-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_alter_branch_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
