# Generated by Django 4.1.7 on 2023-03-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthelper',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commenthelper',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commenthelper',
            name='text_uz',
            field=models.TextField(null=True),
        ),
    ]
