# Generated by Django 4.1.7 on 2023-03-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('size_type', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
                ('format_file', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Music',
                'verbose_name_plural': 'Musics',
            },
        ),
    ]
