# Generated by Django 4.1.7 on 2023-03-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_center_name_en_center_name_ru_center_name_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='image',
            field=models.ImageField(upload_to='centers/%Y/%m'),
        ),
    ]
