# Generated by Django 4.1.7 on 2023-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_center_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='number_students',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
